on:
  push:
    branches:
      - master

name: CI

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: 'x86_64-unknown-linux-gnu' }
          - { os: ubuntu-latest, target: 'wasm32-unknown-unknown' }
          - { os: macos-latest, target: 'x86_64-apple-darwin' }
          - { os: windows-latest, target: 'x86_64-pc-windows-msvc' }
        include:
          - os: ubuntu-latest
            packages: libx11-dev libxi-dev libgl1-mesa-dev gcc-mingw-w64 libasound2-dev
    steps:
      - uses: actions/checkout@v2
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install ${{ matrix.packages }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.config.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.config.target }}
      - name: Upload wasm for pages deploy
        if: matrix.config.target == 'wasm32-unknown-unknown'
        uses: actions/upload-artifact@v2
        with:
          name: wasm_bin
          path: target/${{ matrix.config.target }}/debug/idlep.wasm
          retention-days: 1

  deploy_pages:
    name: Deploy Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: wasm_bin
          path: pages
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: pages
